### ISSUE TITLE
will you release the code of annotation system memtioned in the paper

### ISSUE THREAD

**Issue by jiayolo** [X-LANCE/META-GUI-baseline#2]
hi, thanks for your great works!
when i read your paper:META-GUI: Towards Multi-modal Conversational Agents on Mobile GUI, I found you make an annotation system for your dataset. I really need something like your annotation system. will you release this part of code?I would be very grateful for this.

**Comment by Sunliangtai** [comment]
hi, thanks for your interest in our work. 

Here is the source code of our annotation system. The documents are written in Chinese, if you have any problem, please email me.

[ipa-web-master.zip](https://github.com/X-LANCE/META-GUI-baseline/files/13325727/ipa-web-master.zip)

**Comment by xianqingjia777** [comment]
thanks a lot!

**Comment by jiayolo** [comment]
thanks a lot!

**Comment by jiayolo** [comment]
> hi, thanks for your interest in our work.
> 
> Here is the source code of our annotation system. The documents are written in Chinese, if you have any problem, please email me.
> 
> [ipa-web-master.zip](https://github.com/X-LANCE/META-GUI-baseline/files/13325727/ipa-web-master.zip)

when I follow the documents in the source code and run the sever.py, I got error like this. I think it lacks the necessary files, which are essential when initializing the manager () object.What is the missing file used for? Can you share it if possible?
<img width="679" alt="image" src="https://github.com/X-LANCE/META-GUI-baseline/assets/90776469/fdf9d22b-dfd4-4d88-846e-e95c2e285fd2">
