### ISSUE TITLE
Dataset Access Denied

### ISSUE THREAD

**Issue by mingkaid** [X-LANCE/META-GUI-baseline#5]
![Screenshot 2024-07-01 at 1 26 54 PM](https://github.com/X-LANCE/META-GUI-baseline/assets/13235754/8fdc74aa-77c6-490b-a0ac-2f9ae7aca23b)

I clicked on the dataset download link but got an `Access Denied` error. How can we access the dataset? 

Thanks!

**Comment by Sunliangtai** [comment]
Thanks for your reminder, we have uploaded the dataset to huggingface.
https://huggingface.co/datasets/X-LANCE/META-GUI

**Comment by mingkaid** [comment]
Thank you so much! We will download and try it out.
